# Generated by Django 4.2.18 on 2025-02-08 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('results', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=100)),
                ('number_of_servers', models.IntegerField(default=1)),
                ('service_rate', models.IntegerField(default=0)),
                ('service_distribution', models.CharField(choices=[('Deterministic', 'Deterministic'), ('Exponential', 'Exponential')], default='Deterministic', max_length=30)),
                ('arrival_rate', models.IntegerField(default=0)),
                ('arrival_distribution', models.CharField(blank=True, choices=[('Deterministic', 'Deterministic'), ('Exponential', 'Exponential')], max_length=30, null=True)),
                ('destination_nodes', models.ManyToManyField(blank=True, related_name='source_nodes', to='api.node')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='api.project')),
            ],
            options={
                'ordering': ['project', 'node_name'],
                'unique_together': {('project', 'node_name')},
            },
        ),
    ]
