# Generated by Django 4.2.18 on 2025-02-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_project_options_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='position_x',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='node',
            name='position_y',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='node',
            name='style',
            field=models.JSONField(default=dict),
        ),
    ]
